# Generated by Django 5.0.3 on 2024-03-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nameoncard', models.CharField(max_length=50)),
                ('Creditcardnumber', models.IntegerField()),
                ('Expiration', models.DateTimeField(auto_now_add=True)),
                ('CVV', models.IntegerField()),
            ],
        ),
    ]
